### ISSUE TITLE
Uploaded files do not show up / cannot print

### ISSUE THREAD

**Issue by MetalRush** [gilesdavison/RadaDASH#3] opened 2021-02-27 22:14 UTC
I created a freshly formatted SD card (8Gb) and flashed this card per instructions.
After booting the Pi, the wpa_supplicant.conf -file did not show up in the print-menu of the printer (I waited several minutes, so the Pi had time to boot up). I already setup the WiFi on the printer, so I went ahead and started the webinterface on my pc (http://radadash.local:5000/). The interface showed up and I set the IP address.
The interface connects to the server. The files section on this page showed one file immediately: ERROR1 (I did not print that because it seems pointless). Deleting it, returns a "There has been a problem" message on my screen.
Uploading a sliced file (.pwmx) is possible but the file does not show up in the files section.

![Radadash error](https://user-images.githubusercontent.com/30631800/109401845-5e84b780-7951-11eb-8f28-a9c219161ee1.png)

**Comment by gilesdavison** [comment] 2021-02-28 11:38
Looking into this for a future release, please see: Duplicate of #1

**Closed by gilesdavison** 2021-02-28 11:38 UTC
